version: '3'

services:
  frontend:
    build:
      context: ./project
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
    command: npm run dev

  backend:
    build:
      context: ./bolt_backend
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload